### PR TITLE
significant update

### PR DESCRIPTION
**Pull request by leviwheatcroft**
This PR would be a significant change to your codebase, which you may not appreciate. I don't mean any offense, I'm happy to publish it as a fork if we're unable to merge. 

metalsmith needs a reliable, well maintained webpack implementation, and this one has outstanding issues / PRs 2 years old. If you'd consider adding me as a contributor or transferring ownership I'd be happy to maintain.

fixes:

 * #23 - use debug
 * #22 - webpack dependency

includes PRs:

 * #18 - improved readme
 * #17 - correctly update the metalsmith file index
 * #15 - allow config array
 * #13 - add compilation stats to compiled files object

other improvements:

 * fixed tests (not working in current npm package)
 * cleaner path handling
 * configured babel for transpile, test, and publish
 * backwards compatible to node4
 * updated to ES6 syntax
 * changed callback to promise
 * flexible options (pass string to config file, config array, or options structure)

### CODE REVIEW

**Comment by christophercliff** [comment]
Fair points. I don't intend to maintain this package going forward. I'm open to transferring ownership.

**Comment by leviwheatcroft** [comment]
Hey that's great, anything you need from me before transfer ?

**Comment by christophercliff** [comment]
GitHub refused to transfer because you already have a repo with the same name.

**Comment by leviwheatcroft** [comment]
oh yeah of course. I've renamed the fork so should work now.

**Comment by leviwheatcroft** [comment]
merged into v2 branch

**Pull request closed without merging**
